Add preferred layout name for new product page
Voog/design-reykjavik pull request #134
Opened 2021-03-19 08:34 UTC by robertpih

Related to #133

2021-05-19 13:37 UTC, siimha requested changes

2021-05-19 13:37 UTC, siimha commented on manifest.json
> -      "content_type": "image/svg+xml",
Kas seda ei kasutata? Vaatan, et see on [assetites](https://github.com/Voog/design-reykjavik/tree/master/sources/assets). Kui ei kasutata, siis eemalda ka sealt.

2021-06-09 15:15 UTC, tanelj commented on components/menu-breadcrumbs.tpl
> +<ul class="menu menu-horizontal menu-public menu-breadcrumbs">
Panen kommentaarina. Ka siin oleks korrektsem capturiga UL sisu võtta ja kontrollida `!= blank`. Samas visuaalset pilti see hetkel ei mõjuta.

2021-06-09 15:18 UTC, tanelj approved these changes

2021-06-17 06:34 UTC, siimha approved these changes

2021-06-17 09:39 UTC, merged