Add auto-generated product layout
Voog/design-reykjavik pull request #136
Opened 2022-02-08 12:48 UTC by pxska

* Add auto-generated product layout.
* Add a browser hack for Chrome to render crispier images.
* Also fix underline in product widget grid.

Closes #135.

2022-02-08 18:55 UTC, PeeterPaal requested changes
Looks pretty good, but a few comments too

- [x] Currently gallery is not moved under the buy button in mobile view

2022-02-08 18:55 UTC, PeeterPaal commented on layouts/auto_generated_product.tpl
> +          <div class="content-body product-content-right">
`js-product-content-right` class should be added here

2022-02-08 18:55 UTC, PeeterPaal commented on layouts/auto_generated_product.tpl
> +                <span class="product-price-divider">–</span>
Perhaps add some left and right margin for the price divider

2022-02-09 11:07 UTC, PeeterPaal requested changes
Just one little thing

2022-02-09 11:07 UTC, PeeterPaal commented on layouts/auto_generated_product.tpl
> +          <div class="content-body js-product-content-right">
The product right content is not sticky on scroll. The style rule checks for `product-content-right` class, so let's re-add that
```suggestion
          <div class="content-body js-product-content-right product-content-right">
```

2022-02-10 06:59 UTC, PeeterPaal approved these changes
Great job!

2022-02-10 07:44 UTC, tanelj approved these changes
Nice work!

2022-02-10 12:30 UTC, tanelj requested changes
Nice, but there is one typo.

2022-02-10 13:35 UTC, PeeterPaal approved these changes
Looks good!

2022-02-10 20:47 UTC, merged